name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  steps:
    - uses: hasnep/setup-roc@main
      with:
        roc-version: nightly
    - run: roc test
