name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: drewolson/setup-roc@2e104473064d68ca174075e720397a2342a2d124
        with:
          roc-version: nightly
      - run: roc test
